name: Deploy Fullstack (Backend + Frontend) to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure backend folder exists
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/backend

      - name: Copy backend to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "server/*"
          target: "/home/${{ secrets.EC2_USER }}/backend"
          strip_components: 1
          rm: true

      - name: Build & restart backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/backend

            echo "Ensuring Node.js is installed..."
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            echo "Ensuring PM2 is installed..."
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            npm install
            npm run build

            pm2 delete backend || true
            pm2 start dist/server.js --name backend
            pm2 save


      - name: Ensure frontend folder exists
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/frontend

      - name: Copy frontend to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "client/*"
          target: "/home/${{ secrets.EC2_USER }}/frontend"
          strip_components: 1
          rm: true

      - name: Build & deploy frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/frontend

            npm install
            npm run build
            
            pm2 delete frontend || true
            pm2 serve dist 3000 --name frontend --spa
            pm2 save